### ISSUE TITLE
Wrong way to call exe is used in imgui example on windows

### ISSUE THREAD

**Issue by FreePhoenix888** [conan-io/examples2#132] opened 2024-02-16 13:02 UTC
# Actual
```
cd build\Release
dear-imgui-conan.exe 
```
# Expected
```
cd build\Release
.\dear-imgui-conan.exe 
```
# Reason
```
PS C:\Users\FreePhoenix\Documents\Programming\examples2\examples\libraries\imgui\introduction\build\Release> dear-imgui-conan.exe
dear-imgui-conan.exe: The term 'dear-imgui-conan.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by czoido** [comment] 2024-02-16 14:11
Duplicate: https://github.com/conan-io/examples2/issues/131

**Comment by czoido** [comment] 2024-02-16 14:25
Thanks for reporting, the issue is now fixed: https://github.com/conan-io/conan-io.github.io/pull/261

**Closed** 2024-02-16 14:24 UTC
