### ISSUE TITLE
quote is missed in command for imgui example

### ISSUE THREAD

**Issue by FreePhoenix888** [conan-io/examples2#133] opened 2024-02-16 13:16 UTC
# Actual
```
cmake . -G "Visual Studio 17 2022"
-DCMAKE_TOOLCHAIN_FILE=./build/generators/conan_toolchain.cmake
-DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
```

# Expected
```
cmake . -G "Visual Studio 17 2022"
-DCMAKE_TOOLCHAIN_FILE=./build/generators/conan_toolchain.cmake
-DCMAKE_POLICY_DEFAULT_CMP0091='NEW'
```

**Comment by czoido** [comment] 2024-02-16 14:20
Hi @FreePhoenix888,

Are you finding any problems with the line without singles quotes? In theory, using -DCMAKE_POLICY_DEFAULT_CMP0091=NEW without single quotes should not cause any issues unless there are special characters or spaces involved.

**Comment by czoido** [comment] 2024-02-16 14:25
Thanks for reporting, the issue is now fixed: https://github.com/conan-io/conan-io.github.io/pull/261

**Closed** 2024-02-16 14:24 UTC
